general {
    lock_cmd = pidof hyprlock || hyprlock       # évite de lancer plusieurs instances
    before_sleep_cmd = loginctl lock-session    # verrouille avant la mise en veille
    after_sleep_cmd = hyprctl dispatch dpms on  # réveille l'écran après suspend
}

listener {
    timeout = 300                                # 5 minutes d'inactivité
    on-timeout = loginctl lock-session            # verrouille l'écran
}

listener {
    timeout = 330                                # 5m30
    on-timeout = hyprctl dispatch dpms off        # éteint l'écran
    on-resume = hyprctl dispatch dpms on          # rallume au réveil
}

listener {
    timeout = 900                                 # 15 minutes
    on-timeout = systemctl suspend                # met en veille
}
